### ISSUE TITLE
request help: Can I debug java plugin with apisix deployed by docker on the same instance?

### ISSUE THREAD

**Issue by xueleicug** [apache/apisix-java-plugin-runner#64]
### Issue description
I deployed apisix on my PC by docker and apisix itself works well, at the same time, I want to debug java-plugin on my PC.
Guided by documentation, I imported the apisix-plugin-runner and set up APISIX_LISTEN_ADDRESS and APISIX_CONF_EXPIRE_TIME in environment variables, the java-plugin project started normally and /tmp/runner.sock is created well. In addition, I add related config in the conf.yml of apisix, and I attempt to establish communication between apisix in docker and java-plugin-project, so I mapped volume for sockfile in docker-compose. 
The key configuration is as follows：
in apisix conf.yaml:
```
ext-plugin:
  path_for_test: /tmp/runner.sock
```
in apisix docker-compose file:
```
apisix:
  image: apache/apisix:2.7-alpine
  container_name: apisix
  volumes:
    - /deploy/data/apisix/apisix_log:/usr/local/apisix/logs
    - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml
    - /tmp/runner.sock:/tmp/runner.sock
```
route config
```
{
  "uri": "/xuelei/lion/get",
  "name": "test2",
  "plugins": {
    "ext-plugin-pre-req": {
      "conf": [
        {
          "name": "HeaderPlugin"
        }
      ]
    },
    "proxy-rewrite": {
      "uri": "/lion/get"
    }
  },
  "upstream_id": "369648830490084032",
  "status": 1
}
```

However, it seems that this method does not work, when I send a request to apisix, the request does not go through the java plugin, Is there a problem with my configuration, what else can i do?  Thanks!

### Environment

* apisix-java-plugin-runner version: main
* apisix version: 2.7-alpin
